headless_path = (
	"pickup small shield",
	"use small shield",
	"move north",
	"pickup strength item",
	"use strength item",
	"move south",
	"move east",
	"pickup health item",
	"use health item",
	"sen blood",
	"move east",
	"pickup living quarters' key",
	"move east",
	"move north",
	"pickup hand axe",
	"use hand axe",
	"pickup dining hall key",
	"move north",
	"pickup strength item",
	"use strength item",
	"move north",
	"pickup health item",
	"use health item",
	"pickup short sword",
	"use short sword",
	"move west",
	"pickup health item",
	"use health item",
	"sen water",
	"move west",
	"pickup dining hall exit key",
	"pickup shield",
	"use shield",
	"move south",
	"pickup health item",
	"use health item",
	"unlock west",
	"move west",
	"pickup health item",
	"use health item",
	"pickup battle axe",
	"use battle axe",
	"unlock north",
	"move north",
	"pickup strength item",
	"use strength item",
	"move north",
	"pickup pistol",
	"use pistol",
	"move east",
	"move east",
	"pickup aviary key",
	"move south",
	"pickup strength item",
	"unlock south",
	"move south",
	"pickup saber",
	"use saber",
	"move west",
	"pickup health item",
	"use health item"
	"move east",
	"move south",
	"pickup strength item",
	"use strength item",
	"unlock west",
	"move west"
)